### ISSUE TITLE
Use of <> in Turtle used by p3-check.js and P3 Dashboard without stipulating @base causes problems.

### ISSUE THREAD

**Issue by cblakeley** [fusepoolP3/p3-autoconfiguration-tool#3]
Use of <> in Turtle used by p3-check.js and P3 Dashboard without stipulating @base causes problems using Virtuoso LDP backend.
The actual subject URIs created are not what the Dashboard expects or uses in subsequent queries.

e.g.
POST /DAV/home/fusepool/ldp/platform/tfr/ HTTP/1.1
Host: inspiro:8181
Origin: http://inspiro
...
Slug: XSLT Transformer UI
Referer: http://inspiro/
Accept: */*
Content-Type: text/turtle; charset=UTF-8
Content-Length: 331

<> a <http://vocab.fusepool.info/tfrldpc#TransformerFactoryRegistration> ;  <http://purl.org/dc/terms/title> "XSLT Transformer UI" ;  <http://purl.org/dc/terms/description> "Allows to create XSLT transformers." ;  <http://vocab.fusepool.info/tfrldpc#transformerFactory> <http://inspiro:8204/?transformerBase=http://inspiro:8307> .

----
The created subject URI used is:
<http://localhost:8896/DAV/home/fusepool/ldp/platform/tfr/XSLT%20Transformer%20UI>
not:
<http://inspiro:8181/DAV/home/fusepool/ldp/platform/tfr/XSLT%20Transformer%20UI>

The Dashboard expects subject URIs to use the proxy hostname/port.

----------
Similarly:
The p3-autoconfiguration using <> results in subject URI:
<http://localhost:8896/DAV/home/fusepool/ldp/platform/dcr/default>
whereas the Dashboard issues query:
SELECT * WHERE { <http://inspiro:8181/DAV/home/fusepool/ldp/platform/dcr/default> <http://www.w3.org/ns/ldp#contains> ?child . ...

**Comment by retog** [comment]
Unfortunately the LDP spec has chosen this null-relative URI approach despite better alternatives.

I repeatedly pointed out the bad consequences and the violation of other specs this decision implies. See for example: https://lists.w3.org/Archives/Public/public-ldp/2014Mar/0020.html

In the example the virtuoso LDP instance seems to be misconfiguration (or affected by a bug) as the IRIs for the created resources should be on the same host as the accessed LDPC.
